name: Build develop docker image to Portainer CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: staging
    steps:
      - name: "[preparation] checkout"
        uses: actions/checkout@v4.1.1

      - name: "[preparation] set up golang"
        uses: actions/setup-go@v5.0.0
        with:
          go-version-file: go.mod

      - name: "[preparation] set up qemu"
        uses: docker/setup-qemu-action@v3.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
        with:
          driver-opts: image=moby/buildkit:v0.10.6

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: "build the image to portainer ci with PR number (portainerci/portainer-updater:pr${{ github.event.pull_request.number }})"
        if: ${{ github.event.pull_request.number != '' }}
        run: |
          "${GITHUB_WORKSPACE}/build/build_and_push.sh" portainerci pr$GITHUB_PR_NUMBER

      - name: "build the image to portainer ci (portainerci/portainer-updater:develop)"
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          "${GITHUB_WORKSPACE}/build/build_and_push.sh" portainerci develop
